services:
  - type: web
    name: silv213
    runtime: node
    buildCommand: npm install --production
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=256"
